[package]
repository = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }
name = "contract-macro"
version = "0.1.0"
edition = { workspace = true }
description = "A macro for generating api for ink! contract"

[lib]
proc-macro = true

[dependencies]
heck = "0.4.0"
subxt-codegen = "0.34.0"
ink_metadata = "4.2.0"
contract-metadata = "4.0.0"
proc-macro2 = "1.0.56"
proc-macro-error = { version = "1.0.4", default-features = false }
serde = "1.0.137"
serde_json = "1.0.81"
syn = "2"
quote = "1.0.15"
scale-typegen = "0.2.0"
scale-info = "2.11.0"

[dev-dependencies]
ink_primitives = "4.2.0"
scale-info = { version = "2.5", default-features = false }

[lints]
workspace = true
