[package]
repository = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }
name = "storage-spec"
version = "0.1.0"
edition = { workspace = true }
description = "storage declarations that both server and client need to know"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.4"
blake3 = "1.5.0"

crypto = { workspace = true }
futures = { workspace = true }
berkleamp-welch = { workspace = true }
component-utils = { workspace = true }
codec.workspace = true

[dev-dependencies]
getrandom = "0.2.12"

[lints]
workspace = true
